### ISSUE TITLE
Why is this repository public?

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/neeto-site-eui#14]
@amaldinesh7 _a I don't see any reasons to keep this repo public. Is there anything that I've missed? If not, let's make it private.

question _t

**Comment by amaldinesh7** [comment]
Automatic deployments to Vercel were not happening when it was made private. We have to set up deployment manually if the repo is private I guess. It was not set up since the project was in the initial stage. @AbhayVAshokan

**Comment by neerajdotname** [comment]
The deployment documentation will be taken care of in https://github.com/bigbinary/neeto-engineering-web/issues/296

**Comment by AbhayVAshokan** [comment]
Agreed. Closing this issue as completed.

**Comment by neerajdotname** [comment]
We should keep it open until we make it private. Else we might forget about it.
